### PR TITLE
 IO Forwarding for Tools and Debuggers

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by jjhursey** [comment]
Question:
```
 * payload - pointer to character array containing the data. Note that
 *           multiple strings may be included, and that the array may
 *           _not_ be NULL terminated
 *
 * info - an optional array of info provided by the source containing
 *        metadata about the payload. This could include PMIX_IOF_COMPLETE
 *
 * ninfo - number of elements in the optional info array
 */
 typedef void (*pmix_iof_cbfunc_t)(size_t iofhdlr, pmix_iof_channel_t channel,
                                   pmix_proc_t *source, char *payload,
                                   pmix_info_t info[], size_t ninfo);
```

If the `payload` is not NULL terminated (`'\0'`), then where is the size of the payload stored?

**Comment by jjhursey** [comment]
From teleconf discussion today:

It would be nice to add an "Advice to users" (on the website and in the standard) cautioning them that stdin buffering can be problematic. If a process is slow reading data (or decides never to read data) then we have to buffer the data in the daemon - if they pipe a lot of data then that can be a huge memory footprint. If you have multiple 'sink's then it can compound the issue.

Add an "Advice to implementors" - a high quality implementation will handle a send-to-1 or send-to-all, and sending to a subset of processes can be a challenge...

**Comment by rhc54** [comment]
@jjhursey @dsolt I have updated the RFC per the teleconf - the updated website is here: https://pmix.org/pmix-standard/input-output-forwarding-for-tools/

**Review by jjhursey — DISMISSED** [review]
Per discussion on teleconf. I think this is good to merge so it can start being worked with the other parts of the system.

**Pull request merged**
