### PR TITLE
Define PMIx key to obtain time remaining in a job allocation

### PR DESCRIPTION
**Pull request by adammoody**

### CODE REVIEW

**Comment by rhc54** [comment]
@adammoody Please update text to reference associated code PR

**Comment by rhc54** [comment]
@adammoody I was looking at a way to add the backend support for this to the PMIx reference server, but ran into what appears to be a problem. The SLURM function you cite is in the slurm.h header file, and that code is all GPL. So there doesn't appear to be any way to support this request in the reference server when running under SLURM.

Of course, a SLURM plugin can certainly do so. The Moab interface isn't under GPL, and so I will include support for that one.

**Comment by rhc54** [comment]
@adammoody I added backend support for Moab to the PMIx reference server, branch topic/rfc0013. However, I don't have the required include and libraries to test it. Can you please give it a try?

**Comment by adammoody** [comment]
@rhc54 Great!  Thanks!  Yes, I'll give it a shot this week.

**Comment by adammoody** [comment]
@rhc54 Do you have a URL to the topic/ref0013 branch?  I only see master under the pmix-reference-server repo.

**Comment by jjhursey** [comment]
@adammoody I'm wondering if this isn't the branch he is talking about (not the `pmix-reference-server`, but `pmix-master`):
 * https://github.com/rhc54/pmix-master/tree/topic/rfc0013

It looks like it has some commits on there related to this RFC.

**Comment by adammoody** [comment]
@jjhursey Thanks to your pointer, I tracked down the server here:

https://github.com/rhc54/psrvr/tree/topic/rfc0013

However, when I build this, it no longer seems to install the pmix.h and friends in the install/include directory.  I think this used to work.  Here are the commands I'm using to build:

#!/bin/bash
set -x
installdir=`pwd`/install
export PATH=`pwd`/autotools/install/bin:$PATH

./autogen.pl
#exit 0

export CFLAGS="-g -O0"

./configure \
  --prefix=${installdir} \
  --disable-silent-rules \
   2>&1 > configure.out
#exit 0

make clean
make -j8 VERBOSE=1 2>&1 > make.out
make install 2>&1 > make_install.out

export PATH=`pwd`/install/bin:$PATH
pushd examples
  make VERBOSE=1
popd

The configure/make/make install steps seem to work with the server, but it fails to build the examples, because it doesn't find the pmix.h file.  When I look in the include directory that pcc is pointing to, there are only openmpi and pmix subdirectories -- no headers at this top level.

Back on Jan 18, I did a similar set of commands, and I think it dropped in headers then.  Maybe I'm missing a step though.

Do you know if I need to do anything new to get this to work?

**Comment by rhc54** [comment]
Sorry for delay - was out on vacation. I have a fix coming as soon as it clears CI.

**Comment by rhc54** [comment]
Okay, I have fixed the branch so it now properly installs the headers. Sorry for the problem! There was a change made in the OMPI side that came across on an update and broke the examples.

**Comment by adammoody** [comment]
Thanks.  It compiles now, so that's fixed.

I've got an example client code that issues a time remaining query.  I'm running within a MOAB session.  However, it looks like the pointer to the info object is NULL in the callback.

What is the recommended way for a client to determine that the data is bogus during the callback?

As far as getting to the bottom of why it didn't work, first, it looks like it failed to build the MOAB schizo component:

--- MCA component schizo:moab (m4 configuration macro)
checking for MCA component schizo:moab compile mode... dso
checking --with-moab value... simple ok (unspecified)
checking --with-moab-libdir value... simple ok (unspecified)
checking looking for moab in... (default search paths)
checking mapi.h usability... no
checking mapi.h presence... no
checking for mapi.h... no
checking if MCA component schizo:moab can compile... no

I've modified the configure check to replace "mapi.h" with "moab/mapi.h" and now it at least finds the header (see my pull request).  However, it's still failing to find the MCCJobGetRemainingTime() symbol during the link test.

configure:208002: gcc -std=gnu99 -o conftest -DNDEBUG -g -O0 -Wall -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -pedantic -Werror-implicit-function-declaration -finline-functions -fno-strict-aliasing -pthread -I<dir>/psrvr.git/opal/mca/event/libevent2022/libevent -I<dir>/psrvr.git/opal/mca/event/libevent2022/libevent/include -I<dir>/opal/mca/hwloc/hwloc1113/hwloc/include     conftest.c -lcmoab   -lrt -lm -lutil  -lz  -lrt -lm -lutil  -lz  >&5
conftest.c:523: warning: function declaration isn't a prototype
conftest.c:526: warning: function declaration isn't a prototype
<stuff>/ccKoNFd3.o: In function `main':
<dir>/psrvr.git/conftest.c:527: undefined reference to `MCCJobGetRemainingTime'
collect2: ld returned 1 exit status

We only have libcmoab.a on our system and not libcmoab.so, which lives in /usr/lib64.

Is there a way to have it link with the static .a library?

**Comment by adammoody** [comment]
Oh, wait.  That's not the issue either.  A straight link against libcmoab.a doesn't help.  Let me ping the MOAB support guys here first and come back to you.

**Comment by rhc54** [comment]
We will complete the implementation as @adammoody has available time. The RFC, though, for modifying the standard is approved!

**Comment by adammoody** [comment]
Hooray!

I found out that MOAB dropped the remaining time call from their API some time ago.  I also hear the plan is to support it again in a future release.  However, for now, we don't have a machine at LLNL to test this on.

If we still want to test, perhaps we could add an implementation inside of the SLURM PMIx plugin?

**Pull request merged**
