### PR TITLE
Network Resource Allocations

### PR DESCRIPTION
**Pull request by rhc54**
This RFC extends network integration to add attributes allowing description of a broader range of network configurations and allocation requests.

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by RaymondMichael** [comment]
Thanks for working on this.

**Comment by rhc54** [comment]
@RaymondMichael Please let us know (when you have had time to digest this) if there are gaps or changes required - I know you were concerned about this area, and I hope we at least came close. No problems making adjustments.

**Comment by RaymondMichael** [comment]
As someone who is not familiar with the other PMIx RFCs, I'm reading this as for each process in the job there is one or more data_array collections of info key-value pairs. At job submission time, a user could request one endpoint per process on a particular plane. PMIx and the other infrastructure would allocate the resources and make it easy to look up which endpoint IDs each other process has for a particular Network ID / plane.

Is that in the right ballpark? I may have raised this issue before. It's OK with me for the resource manager to allocate the endpoint IDs and make them easy to look up. I don't want the resource manager configuring them, because each communication middleware implementation likely has very different configuration preferences. Is that going to be an issue here?

**Comment by rhc54** [comment]
You are indeed 100% on target. The RM+PMIx would assign endpoint IDs and make that info available on the backend for each peer, but it would do absolutely nothing with respect to opening or configuring that endpoint - for exactly the reason you note.

**Comment by RaymondMichael** [comment]
Next question. A host has two CPU sockets and two NICs, each NIC directly connected to a socket and both connecting to the same fabric plane. It's fastest to create an endpoint on the NIC connected to socket that a process is pinned to, but there may be reasons not to. We might need all the endpoints to be on the same NIC. Also, the NICs have different namespaces for endpoint IDs. This is knowledge that the middleware author has years of experience with, but the average user doesn't and shouldn't need to know anything about it. How does the problem of figuring out where to create the endpoints get resolved?

**Comment by rhc54** [comment]
Fair question. The discussion relevant to the assignment point revolved around making the endpoint allocation algorithm smart enough to look at minimum distance. Obviously, that would be up to the implementor, but as an implementor, I can say that our plugins (OPA and OPA200) intend to consider distance in their allocation algo.

Key to that are two elements:

1. the call to get the endpoint allocation includes the map of processes - i.e., where each process is going to execute. So we will already know what socket (for example) each process is being placed upon.

1. the companion RFC (https://github.com/pmix/RFCs/pull/30, that has not yet been submitted) to collect the inventory information across the cluster, including relative distance values. This should provide us with adequate info to determine which NIC should be assigned to what process by default.

I think the "default" I mention is important here. Again, it's an implementation issue, but the PMIx implementor can provide support for options (e.g., MCA parameters, or passed pmix_info_t keys) that could help resolve the tailoring concerns if someone knows they are running with OMPI vs MPICH vs Hadoop.

As for the different namespaces: I expect each NIC type will require their vendor to provide a supporting plugin to whatever PMIx implementation is being used on that system. It would be up to them to deal with the namespace issue, I should think - or am I missing something?

**Comment by rhc54** [comment]
I should have pointed something else out. If a middleware vendor had a preferred algorithm for assigning endpoints, then they could certainly provide their own plugin/implementation for doing so. I see no reason why it couldn't be used when executing an application based on that software. I think I also indicated earlier that this could be proprietary, if desired, when using the PMIx reference library's plugin manager.

**Comment by RaymondMichael** [comment]
I can definitely see the need to do implementation-specific allocation of resources. I don't like having to create another plugin, but I can live with it. As a very simple example, before PCIe 4 you can't do coherent atomic memory operations across PCIe, so your primary endpoints all need to be on a single NIC.

**Comment by rhc54** [comment]
You may be correct. However, in that example, we would know that the nodes have PCIe that doesn't support those operations, and so I would expect people to take that into account in their assignments. Perhaps the best way to sum it up is that we'll need to spend time working on the plugins to get things right, and we should expect that we'll encounter situations requiring adjustment as we move forward.

What you've highlighted is the need for sufficient inventory description, and we should capture that in the other RFC (which is next in line for completion). As we get that info, perhaps we can then start to work on some of these assignment-related issues in the existing plugins and see where we hit limitations that might spark the need for additional ones.

Would that correctly summarize the concern? I'm not minimizing it, just trying to capture it.

I may be overly optimistic, but my sense is that we might be able to avoid creating extra plugins (or at least minimize the effort to create a new one by having an adequate base to start from so you just have to deal with corner cases) if we collaborate on the algos and ensure we have adequate inventory descriptions.

The key for now is to try to ensure that this RFC has the correct amount of flexibility in it to allow the plugins to experiment. In other words: do we see anything in this RFC that would prevent someone from writing a plugin that does what they need?

I guess (given that it is just attributes) the question boils down to: does providing the allocation as an array of pmix_info_t somehow prevent us from communicating an envisioned assignment?

**Comment by RaymondMichael** [comment]
I think this RFC looks OK and we've moved on to wider issues.

**Comment by rhc54** [comment]
Thanks - I'll mark it as "seconded" and we'll take it up at the call this week.

**Pull request merged**
