### PR TITLE
Add new RFC for flexible allocations

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by abouteiller** [comment]
A couple questions: 
1. Is the call to "extend/allocate" collective ? If so on what scope ? 
   If not, when is the visibility of the new resources guaranteed (and on what scope) ? 
2. How practically can I pass in some "topology" requirements for the new nodes ? I see the info array for network properties, but I'd like to have an idea of what we envision in practice to handle the case where the new allocation needs to be "on plane x=?,y=?,z=7 of the hypercube" for example.

**Comment by bosilca** [comment]
This is a timely addition. However, if I understand correctly the only info one can specify is about the allocation itself. As a result the group of new processes is totally independent of the process (or processes) that requested their creation and as such might impose undesired overhead to connect them together. I wonder if the spawners can pass information to the spawnees (?) or new processes? If we can have PMIX propagate such information as part of the startup process, we would be able to connect the new processes without having to rely on extra messages going through PMIX.

**Comment by rhc54** [comment]
@abouteiller I honestly wasn't expecting the allocation request to be collective, though I'm open to the idea if you think it would help some use-case. Hadn't really thought about the visibility of the new resources - guess I was assuming they would definitely be visible at the user level in all cases, but only visible to the requesting allocation session if "extend" was given. Still TBD.

I would think the topology requirement would best be passed as a string that the RM would parse, perhaps associated with a key of PMIX_NETWORK_TOPOLOGY?

**Comment by rhc54** [comment]
@bosilca This is strictly for getting/extending/releasing an allocation of resources - nothing would be spawned via this request. So I was expecting a two-stage operation for what you describe:
- request a new or extended allocation of resources
- issue a spawn request targeting the returned resources

You do ask a good question about the spawn API - we can pass info keys to it, and perhaps we should include an attribute to indicate "pass this info to the spawned procs"?

The spawned procs already receive the identity and the job_info of their parents, but we could use this attribute to allow application-directed info as well.

**Comment by marcodamico** [comment]
Hi, do you think the allocation API should be implemented in two ways: blocking and/or non-blocking?
In the non-blocking case should we have another API to check if the allocation was granted?

**Comment by rhc54** [comment]
I guess I was thinking that only a non-blocking was required as (a) getting an allocation can take some time, and (b) the caller can always block themselves by waiting on the callback to occur. However, I don't feel strongly about it.

The callback will tell you if the request was granted or not based on the returned status. I was expecting that the caller could provide a "timeout" value to the request if they want to limit how long they wait.

However, I can see a use-case for someone wanting to query the status of the request, perhaps using a tool. The PMIx_Query interface should adequately cover that situation, and we already have some keys defined that might help - and we can always add more, if needed.

If you want to query the status of this particular request, then we'd need to somehow return a request identifier. Perhaps we should follow the behavior of the event registration APIs? In that case, the initial call to "register" for an event has its own callback that returns the registration ID. Then there is the event callback itself for when the event occurs.

So if we follow that pattern here, the PMIx_Allocation_request API would take a "request recvd" callback function that returns the request ID, and a "request completed" callback function for when the action was completed (successful or not). Alternatively, you could just block in the initial PMIx_Allocation_request call and return the request ID there - this would be a simpler API and minimize the parameter list.

Thoughts?

**Comment by bosilca** [comment]
@rhc54 I think we need to extend this interface with a peer-provided key, that can be used by any process to inquiry the state of the allocation. This will be needed in volatile environments, where the process that made the request might disappear before the request is satisfied by the RM. 

Here is a plausible scenario. If a process dies (at this point this process is the only point of contact between the RM and the rest of the processes) after requesting a new allocation but before the allocation completes, we reach a dead-end. The RM cannot simply drop the request because it might not yet know the status of the requester process, and the other processes have no way to contact the RM with regard to the allocation request (because the request is not named).

If we can provided name for each allocation request (the uniqueness of the name will be in charge of the requester), then we can assume that a well designed library would have propagated this name between all the interested participants, before asking for the allocation. Thus, even if the process that requested the allocation dies, the remaining participants have a way to retrieve the info about the allocation from the RM.

**Comment by rhc54** [comment]
Fair enough - do you think we need to add this as a discrete parameter? Or would an attribute in the pmix\_info\_t array be sufficient? The latter would make it easier for the remaining participants to query about the allocation via the PMIx\_Query API.

**Comment by rhc54** [comment]
@bosilca I have updated the RFC per your suggestion, and included the example program

**Comment by bosilca** [comment]
@rhc54 thanks. I think the PMIX_ALLOC_ID should also be set upon the root request. I can't access the RFC, but I think we are missing 
```c
PMIX_INFO_LOAD(&info[0], PMIX_ALLOC_ID, myallocation, PMIX_STRING);
```
after line 192.

**Comment by rhc54** [comment]
Duh - yes indeed. will fix

**Comment by rhc54** [comment]
Updated - thx!

**Comment by rhc54** [comment]
@bosilca Would you mind reviewing this for me? I added the ability for other procs to not only poll (via query) for allocation status, but also to register for allocation events. I think this is now complete.

Let me know if it looks okay and I'll mark it as "seconded" - or you should be able to mark that label yourself, if you like.

**Comment by bosilca** [comment]
@rhc54 good addition. What is the expected behavior if a query or registration for an allocation update is issued before the allocation was been asked by it's creator?

**Comment by rhc54** [comment]
On a query, if the request hasn't been recorded yet, you'll get a "not found" response. If the request has been recorded, then you'll get its status.

Event notifications, however, are cached. So if you register for an event that hasn't been generated yet, then we just record the registration until the event occurs. If the event occurs before you register, then we cache it and you'll be notified as soon you do register.

This illustrates the primary downside to the query - you have to keep querying until you get a "done" or "denied" response.

**Comment by jjhursey** [comment]
Refs https://github.com/pmix/master/pull/314

**Comment by jjhursey** [comment]
I think this looks good.

The only (minor) item I had was the name of `PMIX_ERR_ALLOC_COMPLETE` seems off to me. It's not really an error, but a notification back to the client (right?). It seems odd to have it marked as `_ERR_` in that case. Maybe `PMIX_NOTICE_ALLOC_COMPLETE` would be better?

I'm fine keeping it the way it is if that is what you all intended, but I just wanted to throw that out there.

**Pull request merged**
